## Mihomosh configs

# Mihomo config file path (REQUIRED)
mihomo-path: /etc/mihomo/config.yaml

# Mihomo external controller URL (REQUIRED)
mihomo-api: http://127.0.0.1:9090

# Mihomo external controller secret (Optional)
#mihomo-secret: input-your-secret-here

# Log level (REQUIRED; One of `silent`, `error`, `warning`, `info` or `debug`)
log-level: info

# Proxy mode (REQUIRED; One of `rule`, `global` or `direct`)
mode: rule

# HTTP(S) port (Optional)
port: 7890

# Socks port (Optional)
#socks-port: 7891

# Mixed port (Optional)
#mixed-port: 7892

# Allow LAN (REQUIRED)
allow-lan: false

# Allow IPv6 (REQUIRED)
allow-ipv6: false

# Unified delay (REQUIRED)
unified-delay: true
